// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weddingplanner.Models;

namespace weddingplanner.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("weddingplanner.Models.Association", b =>
                {
                    b.Property<int>("associationID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("userID");

                    b.Property<int>("weddingID");

                    b.HasKey("associationID");

                    b.HasIndex("userID");

                    b.HasIndex("weddingID");

                    b.ToTable("associations");
                });

            modelBuilder.Entity("weddingplanner.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("firstname")
                        .IsRequired();

                    b.Property<string>("lastname")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("userID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("weddingplanner.Models.Wedding", b =>
                {
                    b.Property<int>("weddingID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<DateTime>("date");

                    b.Property<int>("userID");

                    b.Property<string>("wedder1")
                        .IsRequired();

                    b.Property<string>("wedder2")
                        .IsRequired();

                    b.HasKey("weddingID");

                    b.HasIndex("userID");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("weddingplanner.Models.Association", b =>
                {
                    b.HasOne("weddingplanner.Models.User", "attendee")
                        .WithMany("attendingweddings")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("weddingplanner.Models.Wedding", "wedding")
                        .WithMany("attendees")
                        .HasForeignKey("weddingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("weddingplanner.Models.Wedding", b =>
                {
                    b.HasOne("weddingplanner.Models.User", "planner")
                        .WithMany("plannedweddings")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
